import { Inter } from "next/font/google";
import "./globals.css";
import UseServerDarkMode from "@/hooks/use-server-dark-mode";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s | Finance App",
    default: "Finance App",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const theme = await UseServerDarkMode();
  return (
    <html lang="en" className={theme}>
      <body
        className={` ${inter.className} antialiased flex flex-col min-h-screen px-8`}
      >
        {children}
      </body>
    </html>
  );
}
